services:
  connect4-developer:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    environment:
      - RELEASE_NAME="connect4-service"
    volumes:
      - .:/home/app
    entrypoint: "tail -f /dev/null"
    ports:
      - "50051:50051"
